export const browserCoreExamples = [
  "rgbot browser status",
  "rgbot browser start",
  "rgbot browser stop",
  "rgbot browser tabs",
  "rgbot browser open https://example.com",
  "rgbot browser focus abcd1234",
  "rgbot browser close abcd1234",
  "rgbot browser screenshot",
  "rgbot browser screenshot --full-page",
  "rgbot browser screenshot --ref 12",
  "rgbot browser snapshot",
  "rgbot browser snapshot --format aria --limit 200",
  "rgbot browser snapshot --efficient",
  "rgbot browser snapshot --labels",
];

export const browserActionExamples = [
  "rgbot browser navigate https://example.com",
  "rgbot browser resize 1280 720",
  "rgbot browser click 12 --double",
  'rgbot browser type 23 "hello" --submit',
  "rgbot browser press Enter",
  "rgbot browser hover 44",
  "rgbot browser drag 10 11",
  "rgbot browser select 9 OptionA OptionB",
  "rgbot browser upload /tmp/file.pdf",
  'rgbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "rgbot browser dialog --accept",
  'rgbot browser wait --text "Done"',
  "rgbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "rgbot browser console --level error",
  "rgbot browser pdf",
];
